security:
    encoders:
        Symfony\Component\Security\Core\User\User: bcrypt
        App\Entity\User:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        chain_provider:
            chain:
                providers: [in_memory, user_db]
        user_db:
            entity:
                class: App\Entity\User

        in_memory:
            memory:
                users:
                    delrodie:
                        password: $2y$12$cjh9Smofl7ud4fauPSwowu4F2t1K.x9r6Uri7e08oKYu7noBZu3Ua
                        roles: 'ROLE_SUPER_ADMIN'

                    admin:
                        password: $2y$12$FUWZ8nebMvi49ZjmjKFBWOw8DVEWzyz8IKmSFvvapM7T.msLrblta #toursdivoire2018
                        roles: 'ROLE_ADMIN'
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            provider: user_db
            anonymous: ~
            pattern: ^/
            #http_basic: ~

            # activate different ways to authenticate

            http_basic:
                realm: 'Secured demo area'
                provider: in_memory
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # https://symfony.com/doc/current/security/form_login_setup.html
            form_login:
                login_path: login
                check_path: login
                csrf_token_generator: security.csrf.token_manager
                #csrf_token_id: a_private_string

            logout:
                path: /logout
                target: /

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/article, roles: ROLE_USER }
        - { path: ^/localite, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/admin/user, roles: ROLE_SUPER_ADMIN }
