vich_uploader:
    db_driver: orm

    mappings:
        post_image:
            uri_prefix: /upload/posts
            upload_destination: '%kernel.project_dir%/public/upload/posts'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
